### PR TITLE
Issue 12 wireframes for frontend

### PR DESCRIPTION
**Pull request by SamskiUchiha**

### CODE REVIEW

**Review by KeithSantamaria — APPROVED** [review]
This should be fine, but there a lack of EOF token on the base .gitignore

So we should be on the lookout

**Review by JMantis0 — APPROVED** [review]
Wireframes

**Comment by KeithSantamaria** [comment]
I also just popped in the newly made diagram in this PR, and I even renamed the directory to be lower case

**Review by KAltieri — APPROVED** [review]
nice

**Pull request merged**
